version: "3.7"
services:
  web:
    # 以下2行は、byebugを使えるように
    stdin_open: true
    tty: true
    build: .
    container_name: web
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle install && rails s -b '0.0.0.0' -p 3000"
    volumes:
      - .:/api
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
